spring:
  jpa:
    show-sql: true    
  http:
    encoding:
      charset: UTF-8
   
       
logging:
  level:  
    root: INFO
    com:
      fr:
        general:
          FRLogger: INFO